### ISSUE TITLE
plot_terse_amdahl_results corrupts data

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/HPC-workflow-lesson-maestro#4]
If invoked improperly, the script can corrupt input files.
If invoked without arguments, the script does not print a help statement.
The source code itself is not well-documented for its expected invocation.
The script uses the default Matplotlib backend, which is not appropriate for cluster jobs.
Set the 'Agg' backend to avoid GTK errors.

Pinging @ocaisa, as this applies upstream as well.

**Comment by xorJane** [comment]
This was resolved thanks to @tkphd's [commits on June 4 and 5](https://github.com/xorJane/maestro-workflow-lesson/commits/main/episodes/files/plot_terse_amdahl_results.py).
